### ISSUE TITLE
"redis.addCommand is not a function"

### ISSUE THREAD

**Issue by jesse-a-reilly** [stockholmux/node_redis-redisearch#1]
Running the initialisation code:
```
var
   redis       = require('redis'),
   redisearch  = require('redis-redisearch');

redisearch(redis);
```
returns the error:
```
/node_modules/redis-redisearch/index.js:2
  redis.addCommand('ft.create');
        ^

TypeError: redis.addCommand is not a function
    at addRediSearchModule (/.../node_modules/redis-redisearch/index.js:2:9)
    at Object.<anonymous> (/.../app.js:49:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Looking at index.js, there's no require statements, and there are no dependencies listed in package.js - is the package missing some dependencies?

**Comment by stockholmux** [comment]
What version of node_redis are you using?

**Comment by jesse-a-reilly** [comment]
Ah, I was trying to use this with ioredis.
Looks like the problem was in the chair, not the computer >.>
